jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --gc
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './jungH4X0r.github.io'
